wiki:
  domain: "https://wiki.eniot.io/"
  username: "yue.zhang5"
  password: ""

vector_db:
  persist_directory: "/Users/zhangyue/Documents/code/AI/chroma_db"
  chunk_size: 200
  overlap: 50

app:
  host: "0.0.0.0"
  port: 8080
  debug: True

siliconflow:
  api_key: ""